install:
  - export PATH=$GOPATH/bin:$PATH
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/dchest/uniuri

script: ginkgo -r --randomizeSuites -race -cover

language: go

go:
  - 1.8
  - 1.9
  - tip
